from .interfaces import ISparcBytesContentAvailableEvent
from .interfaces import ISparcBytesFile
from .interfaces import ISparcBytesFileContent
from .interfaces import ISparcContentAvailableEvent
from .interfaces import ISparcFile
from .interfaces import ISparcFileContent
from .interfaces import ISparcFileContentsLocator
from .interfaces import ISparcFileReader
from .interfaces import ISparcFileReaderTail
from .interfaces import ISparcFileReaderWithBookmark
from .interfaces import ISparcUnicodeContentAvailableEvent
from .interfaces import ISparcUnicodeFile
from .interfaces import ISparcUnicodeFileContent